apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: register-artifact
description: "Register Artifact"

inputs:
  artifactName:
    type: string
    required: true
  baseVersion:
    type: string
    required: true
  digest:
    type: string
    required: false

runs:
  using: composite
    steps:
      - uses: cloudbees-io/register-build-artifact@v1
        name: Publish artifact
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{inputs.baseVersion}}-${{cloudbees.version}}"
          url: "docker.io/MyApp/${{ inputs.artifactName }}:${{inputs.baseVersion}}-${{cloudbees.version}}"
          digest: "${{ inputs.digest }}"          
